name: housing
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pandas=2.1.1
- scikit-learn=1.3.1
- flask=2.1.1
- werkzeug=2.0.3
- streamlit=1.24.1
- shap=0.41.0
- requests=2.28.1
- mlflow
- requests
- flask-cors