version: '3.8'

services:
  flask_api_v1:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5005:5003"
    environment:
      - FLASK_APP=api.v1.main
    networks:
      - app_network
    volumes:
      - ./api:/app/api
      - ./model:/app/model
      - ./data:/app/data

  flask_api_v2:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5006:5003"
    environment:
      - FLASK_APP=api.v2.main
    networks:
      - app_network
    volumes:
      - ./api:/app/api
      - ./model:/app/model
      - ./data:/app/data

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    networks:
      - app_network
    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py

networks:
  app_network:
    driver: bridge