version: '3.8'

services:
  flask_api_v1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"  # Host port 5003 mapped to container port 5003
    environment:
      - FLASK_APP=app/api/v1/main.py

  flask_api_v2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5003"  # Host port 5004 mapped to container port 5003
    environment:
      - FLASK_APP=app/api/v2/main.py

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
