#ci-cd pipeline for the real estate model
name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        conda env create -f conda_environment.yml

    - name: Lint code
      run: |
        flake8 .

    - name: Build Docker images
      run: |
        docker build -t real_estate_model .
        docker build -t streamlit_app -f Dockerfile.streamlit .

    - name: Run tests
      run: |
        docker run -d -p 5003:5003 real_estate_model
        docker run -d -p 8501:8501 streamlit_app
        python app/api/test_api.py
